config/routes.rb
Rails.application.routes.draw do
	get 'todos', to: 'todos#index'
	get 'todos/new'
	post 'todos', to: 'todos#create'
	get 'todos/:id', to: 'todos#show', as:'todo'
	get 'todos/:id/edit', to: 'todos#edit'
	patch 'todos/:id', to: 'todos#update'
	delete 'todos/:id', to: 'todos#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
 		@todo = Todo.all
 	end

 	def new
 		@todo = Todo.new
 	end

 	def create
		@todo = Todo.new(params[:id])
		@todo.save 
		redirect_to todos_path
	end

	def show
		@todo= Todo.find(params[:id])
	end

	def update
		@todos = Todo.find(params[:id])
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end

	private

	def todo_params
		params.require(:todo).permit(:description, :completed)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>


    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<% form_with model: @todo, local true @todo do|f|%>
	<% f.label :description,"description"%>
	<% f.text_field: description%>
	<%= f.label :completed, "completed"%>
	<%= f.number_field :completed %>
	<% f.submit "Enviar"%>
<% end%>

app/views/todos/index.html.erb
<% @todo.each do |todo| %>
 	 <h1> <%= todo.description %> </h1>
 	 <p> <%= link_to 'Borrar',todo_path(todo.id), method: :delete %> </p> 
<% end %>

 	 <p> <%= link_to 'Crear', todos_new_path  %> </p>

app/views/todos/new.html.erb
<%= form_with model: @todo, local: true do |f|%>
	<%= f.label :description,"description"%>
	<%= f.text_field :description %>
	<%= f.label :completed, "completed"%>
	<%= f.number_field :completed %>
	<%= f.submit "Enviar"%>
<% end%>

app/views/todos/show.html.erb
	<h1> <% todo.description %> </h1>
	<p> <% todo.completed%> </p> 